import {
  Atom,
  BookOpen,
  Brain,
  Briefcase,
  Church,
  Compass,
  Cpu,
  Drama,
  Dumbbell,
  FlaskConical,
  Globe,
  Landmark,
  Languages,
  Leaf,
  Microscope,
  Music,
  NotebookPen,
  Palette,
  Scale,
  Scroll,
  Sigma,
  Sparkles,
  Users,
  type LucideIcon,
} from 'lucide-react'

const ICON_MAP: Record<string, LucideIcon> = {
  'book-open': BookOpen,
  sigma: Sigma,
  languages: Languages,
  scroll: Scroll,
  leaf: Leaf,
  'flask-conical': FlaskConical,
  atom: Atom,
  cpu: Cpu,
  microscope: Microscope,
  landmark: Landmark,
  globe: Globe,
  scale: Scale,
  users: Users,
  briefcase: Briefcase,
  compass: Compass,
  church: Church,
  brain: Brain,
  palette: Palette,
  music: Music,
  dumbbell: Dumbbell,
  drama: Drama,
  'notebook-pen': NotebookPen,
}

export function getSubjectIcon(iconKey: string): LucideIcon {
  return ICON_MAP[iconKey] ?? Sparkles
}
